package com.nagar_sewak.backend.entities;

public enum NotificationType {
    COMPLAINT_CREATED,
    COMPLAINT_STATUS_CHANGED,
    COMPLAINT_ASSIGNED,
    COMPLAINT_COMMENTED,
    COMMENT,
    MENTION,
    TENDER_NEW_OPPORTUNITY,
    TENDER_SUBMITTED,
    TENDER_BID_ACCEPTED,
    TENDER_BID_REJECTED,
    TENDER_DEADLINE_REMINDER,
    PROJECT_UPDATE_REQUIRED,
    PROJECT_COMPLETED,
    RATING_LOW_SCORE,
    SYSTEM_ANNOUNCEMENT,
    SYSTEM_ALERT
}
