package com.nagar_sewak.backend.entities;

public enum SecurityEventType {
    FAILED_LOGIN_ATTEMPT,
    SUCCESSFUL_LOGIN,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    NEW_DEVICE_LOGIN,
    PASSWORD_CHANGED,
    MFA_ENABLED,
    MFA_DISABLED,
    MFA_VERIFICATION_FAILED,
    SUSPICIOUS_ACTIVITY_DETECTED,
    DATA_EXPORT_REQUESTED,
    ACCOUNT_DELETION_REQUESTED,
    EMAIL_NOTIFICATION_SENT,
    EMAIL_NOTIFICATION_FAILED,
    DEVICE_TRUSTED,
    DEVICE_UNTRUSTED
}